---
title: "Homework 10 - web scraping using httr"
author: "Rowenna Gryba"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    keep_md: yes
---

# Scraping with `httr`
## Read in required libraries
```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(httr))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
```

## eBirds website - take 2!
Getting info off the eBirds site seemed overly hard with `rvest` - trying it again and we shall see if it's easier.

Let's get the most recent notable sightings for Alaska.

First load the data.
```{r}
eB <- GET("https://ebird.org/ws2.0/data/obs/US-AK/recent?detail=full&key=4djb9hct7gta")
names(eB)
status_code(eB) #status 200 - so good to go
```
Yup! API makes it much easier. 

Next let's build a table of the species sighted and the date they were seen.
```{r}
ebAK <- content(eB) 
ebAK <- ebAK %>% {
	tibble(
		sp = map_chr(., "sciName"),
		date = map(., "obsDt")
	)
}

kable(head(ebAK)) %>%
	kable_styling()

```